### ISSUE TITLE
Issues (no response) when using getContents() on the WebSocketStream

### ISSUE THREAD

**Issue by Sebastix** [valtzu/guzzle-websocket-middleware#1]
Thank for creating this neat piece of middleware for using the Http/Guzzle client with websockets!

Here is snippet where I expect a string (a response from the relay) to be returned when using the `getContents` function from the WebSocketStream class.

```php

$handlerStack = new HandlerStack(new StreamHandler());
$handlerStack->push(new WebSocketMiddleware());

$guzzle = new Client(['handler' => $handlerStack]);

$handshakeResponse = $guzzle->request('GET', 'wss://ws.postman-echo.com/raw');
$ws = $handshakeResponse->getBody();

$ws->write("Hello world");
$ws->read(0);
$content = $ws->getContents();
echo $content;
```

When the timeout limit is reached (I suppose?) and the stream is dropped, $content returns `��`.

I do find the content I'm looking for in the buffer property of the `$ws` WebSocketStream.
When I replace (https://github.com/valtzu/guzzle-websocket-middleware/blob/main/src/WebSocketStream.php#L130)
```php
return $this->connection->getContents();
```
with 
```php
return $this->buffer->getContents();
```
it works with another websocket URL (a Nostr relay).

I'm not a Websocket expert, so maybe you could clarify things a bit here :)

**Comment by valtzu** [comment]
Thanks for opening the first issue!

It seems the `getContents()` is lacking tests. What did you expect to happen when calling it? The current behavior indeed seems incorrect – the protocol details should not leak outside the stream class.

With the current implementation, you should always use f.e. `$ws->read(1000);` – the reading will stop once the message is received anyway so you can put a large number there.

Maybe it would make sense to just throw when calling `getContents()` since it does not make much sense in web socket context, given WS is a two-way protocol and `getContents()` is one-way + it reads the whole stream till the end (until timeout, like you experienced).

**Comment by valtzu** [comment]
I made `$length` in `read()` optional, and `read()`, `getContents()` & `__toString()` are now synonyms.

Could you try if 0.2.0 release resolves your issue? :slightly_smiling_face:

**Comment by Sebastix** [comment]
Yes, this resolved my issue indeed! Thanks for your quick follow-up! As I'm just digging into this (Websockets), I expect to have more questions and/or feature requests ;) 

So now `$ws->read();` and `$ws->getContents();` do return the same, correct?

**Comment by valtzu** [comment]
Great!

> So now `$ws->read();` and `$ws->getContents();` do return the same, correct?

Correct, but I would encourage to use `read()` because `getContents()` now behaves a bit counter-intuitive in my opinion – and I may make it always throw like I mentioned in https://github.com/valtzu/guzzle-websocket-middleware/issues/1#issuecomment-2359047781.


---

I'm closing this issue as done, feel free to open a new one if you have more questions / issues.
